# Generated by Django 3.2.9 on 2022-04-01 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ФИО (или псевдоним) автора', max_length=200, verbose_name='ФИО')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, default='./static/images/default.png', upload_to='./static/images/author/')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, help_text='Введите дату рождения автора: yyyy-mm-dd', verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(default=django.utils.timezone.now, help_text='Введите дату смерти автора: yyyy-mm-dd', verbose_name='Дата смерти')),
                ('description', models.TextField(default='Описание отсутствует.', help_text='Введите описание автора', max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название книги', max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, default='./static/images/default.png', upload_to='./static/images/book/')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(default='Описание отсутствует.', help_text='Введите описание книги', max_length=1000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Введите цену книги', max_digits=13, verbose_name='Цена')),
                ('format', models.CharField(choices=[('AU', 'Аудио'), ('TXT', 'Текст')], default='TXT', help_text='Выберите формат книги: аудио или текст', max_length=20, verbose_name='Формат')),
                ('writing_date', models.DateField(default=django.utils.timezone.now, help_text='Введите дату написания книги: yyyy-mm-dd', verbose_name='Дата написания')),
                ('language', models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский')], default='Русский', help_text='Выберите язык книги', max_length=20, verbose_name='Язык')),
                ('author', models.ManyToManyField(related_name='books', to='catalog.Author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Введите стоимость заказа', max_digits=13, verbose_name='Стоимость')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Введите дату создания заказа: yyyy-mm-dd', verbose_name='Дата заказа')),
                ('composition', models.ManyToManyField(to='catalog.Book', verbose_name='Состав заказа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['cost'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название купона', max_length=200, verbose_name='Купон')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Введите описание купона', max_length=1000, verbose_name='Описание')),
                ('discount', models.PositiveSmallIntegerField(default=0, help_text='Введите скидку по купону в %', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка по купону')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название издателя', max_length=200, verbose_name='Издатель')),
                ('image', models.ImageField(default='./static/images/default.png', upload_to='./static/images/publisher/')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(default='Описание отсутствует.', help_text='Введите описание издателя', max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Приключение', 'Приключение'), ('Роман', 'Роман'), ('Юмор', 'Юмор'), ('История', 'История'), ('Любовный роман', 'Любовный роман'), ('Триллер', 'Триллер'), ('Психология', 'Психология'), ('Реализм', 'Реализм'), ('Пост-апокалипсис', 'Пост-апокалипсис'), ('Мистика', 'Мистика'), ('Для детей', 'Для детей'), ('Обучение', 'Обучение')], help_text='Введите название тэга', max_length=100, verbose_name='Тэг')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(default='Описание отсутствует.', help_text='Введите описание тэга', max_length=1000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст цитаты', max_length=1000, verbose_name='Текст цитаты')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.book')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Купленная книга пользователя',
                'verbose_name_plural': 'Купленные книги пользователей',
                'ordering': ['book'],
            },
        ),
        migrations.CreateModel(
            name='PublisherBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.publisher')),
            ],
            options={
                'verbose_name': 'Список книг у издателя',
                'verbose_name_plural': 'Списки книг у издателей',
                'ordering': ['publisher'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Любимая книга пользователя',
                'verbose_name_plural': 'Любимые книги пользователей',
                'ordering': ['book'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.author')),
            ],
            options={
                'verbose_name': 'Любимый автор пользователя',
                'verbose_name_plural': 'Любимые авторы пользователей',
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='BuyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.book')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.buy')),
            ],
            options={
                'verbose_name': 'Состав заказ',
                'verbose_name_plural': 'Составы заказов',
                'ordering': ['buy'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(related_name='books', to='catalog.Tag', verbose_name='Тэг'),
        ),
        migrations.CreateModel(
            name='AuthorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.book')),
            ],
            options={
                'verbose_name': 'Авторы книги',
                'verbose_name_plural': 'Авторы книг',
                'ordering': ['author'],
            },
        ),
    ]
