# Generated by Django 3.2.9 on 2022-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_favoritebook_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritebook',
            name='book',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='user',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
