# Generated by Django 3.2.9 on 2022-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_purchasedbook_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedbook',
            name='book',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedbook',
            name='user',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
