# Generated by Django 3.2.9 on 2022-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_author_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='books',
            field=models.ManyToManyField(related_name='publishers', to='catalog.Book', verbose_name='Книги'),
        ),
    ]
