# Generated by Django 3.2.9 on 2022-05-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_publisher_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
    ]
