# Generated by Django 3.2.9 on 2022-05-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='buycomposition',
            name='book',
        ),
        migrations.RemoveField(
            model_name='buycomposition',
            name='buy',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='books',
        ),
        migrations.RemoveField(
            model_name='publisherbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='publisherbook',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('AUDIO', 'Аудио'), ('TXT', 'Текст')], default='TXT', help_text='Выберите формат книги: аудио или текст', max_length=20, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='BuyComposition',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='PublisherBook',
        ),
    ]
