# Generated by Django 3.2.9 on 2022-05-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20220514_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorBook',
        ),
    ]
