# Generated by Django 3.2.9 on 2022-05-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=255, null=True)),
                ('quote', models.CharField(default=None, max_length=255, null=True)),
                ('session_key', models.CharField(default=None, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Любимая цитата пользователя',
                'verbose_name_plural': 'Любимые цитаты пользователей',
                'ordering': ['user'],
            },
        ),
    ]
