# Generated by Django 3.2.9 on 2022-05-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_favoritequote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedbook',
            name='session_key',
        ),
    ]
