# Generated by Django 3.2.9 on 2022-05-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_purchasedbook_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteauthor',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='favoritebook',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='favoritequote',
            name='session_key',
        ),
    ]
